# Generated by Django 5.1.6 on 2025-04-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image'),
        ('onlineshop', '0004_order_client_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pb_can_be_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='products_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_bought', to='onlineshop.product'),
        ),
        migrations.AddField(
            model_name='relations',
            name='is_blocking',
            field=models.BooleanField(default=False),
        ),
    ]
