# Generated by Django 5.1.6 on 2025-04-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_pb_can_be_seen_profile_products_bought_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pb_can_be_seen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='products_bought',
        ),
    ]
