# Generated by Django 5.1.6 on 2025-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_alter_product_options_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('delivered', 'DELIVERED'), ('denied', 'DENIED'), ('shipping', 'SHIPPING')], default='pending', max_length=100),
        ),
    ]
