# Generated by Django 5.1.6 on 2025-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_order_address_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_info',
            field=models.CharField(default='', max_length=50),
        ),
    ]
