# Generated by Django 5.1.6 on 2025-09-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookMarks',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
